name: Convert Ruleset to MRS
on:
  #push:
  #branches:
  #- ruleset
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "GOAMD64=v3" >> $GITHUB_ENV
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Checkout KuGouGo/Rules
        uses: actions/checkout@v4
        with:
          #fetch-depth: 0
          ref: mihomo

      - name: Checkout MetaCubeX/meta-rules-converter
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/meta-rules-converter
          path: convert

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Convert asn
        run: |
          mkdir -p mihomo-rule/asn
          cd convert
          wget https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb
          go run ./ asn -o ../mihomo-rule/asn

      - name: Combine asn
        run: |
          mkdir -p mihomo-rule/asn/china-asn
          cd convert
          wget https://raw.githubusercontent.com/ForestL18/ASN/main/China-ASN.list
          go run ./ combine -a ./ -i ../mihomo-rule/asn -o ../mihomo-rule/asn/china-asn

      - name: Convert domain files to MRS
        run: |
          mkdir -p mihomo-rule/geo/domain
          cd convert
          shopt -s nullglob
          cp ../geo/domain/*.{list,yaml,yml} ../mihomo-rule/geo/domain
          go run ./ textfile -i ../geo/domain -o ../mihomo-rule/geo/domain -b domain

      - name: Convert ipcidr files to MRS
        run: |
          mkdir -p mihomo-rule/geo/ipcidr
          cd convert
          shopt -s nullglob
          cp ../geo/ipcidr/*.{list,yaml,yml} ../mihomo-rule/geo/ipcidr
          go run ./ textfile -i ../geo/ipcidr -o ../mihomo-rule/geo/ipcidr -b ipcidr

      - name: Commit and push changes
        run: |
          cd mihomo-rule
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b mihomo
          git add .
          git commit -m "Released on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin mihomo
