name: Fork & Edit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6,18 * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: KuGouGo/Rules
        path: Rules-repo

###### Clash

    - name: Copy Clash/Rules
      run: |
        mkdir -p Rules/{Clash,Loon}/Rules
        # 流媒体
        cp -r Rules-repo/Loon/Rules/Emby.list Rules-repo/Clash/Rules/Emby.list
        # AI
        curl -L -o Rules-repo/Clash/Rules/AI.list "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ai.list"
        # fakeip-filter
        curl -L -o Rules-repo/Clash/Rules/fakeip-filter.list "https://raw.githubusercontent.com/juewuy/ShellCrash/master/public/fake_ip_filter.list"

      # 适配规则
    - name: Edit Clash/Rules
      run: |
        cd Rules-repo/Clash/Rules
        for file in *.list; do
          if [ "$file" != "ChinaIPv4.list" ] && [ "$file" != "ChinaIPv6.list" ] && [ "$file" != "Lan.list" ]; then
            sed -i -e 's/, /,/g' \
                   -e 's/;/# /g' \
                   -e 's/host,/HOST,/g' \
                   -e 's/host-/HOST-/g' \
                   -e 's/-suffix/-SUFFIX/g' \
                   -e 's/-keyword/-KEYWORD/g' \
                   -e 's/ip-cidr/IP-CIDR/g' \
                   -e 's/geoip/GEOIP/g' \
                   -e 's/HOST,/DOMAIN,/g' \
                   -e 's/HOST-/DOMAIN-/g' \
                   -e 's/IP6-CIDR,/IP-CIDR6,/g' \
                   -e 's/,REJECT$//g' \
                   -e 's/,DIRECT$//g' \
                   -e 's/,reject$//g' \
                   -e 's/,direct$//g' \
                   -e 's/,extended-matching$//g' \
                   -e '/# 内容：/d' \
                   -e '/# 数量：/d' \
                   -e '/# 更新：/d' \
                   -e '/# NAME:/d' \
                   -e '/# AUTHOR:/d' \
                   -e '/# REPO:/d' \
                   -e '/# UPDATED:/d' \
                   -e '/404: Not Found/d' \
                   "$file"
          fi
        done

      # 去重排序
    - name: Remove duplicates and lines 
      run: |
        cd Rules-repo/Rules
        shopt -s nullglob  # 避免没有匹配的文件时保留原始通配符
        for file in Reject.list; do
          if [ -f "$file" ]; then
            sorted_file="sorted_${file}"
            # 使用 grep 去掉包含 # 的行
            grep -v '^\s*#' "$file" | grep -v '^\s*$' | sort | uniq > "$sorted_file"
            mv "$sorted_file" "$file"
          else
            echo "$file not found."
          fi
        done
      shell: bash       

###### Commit
    - name: Add and Commits
      run: |
        cd Rules-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
